### ISSUE TITLE
problem defining N x 1 matrices 

### ISSUE THREAD

**Issue by mboedigh** [brian-lau/MatlabStan#15]
I looked to see if this issue was already posted, but didn't find it. Sorry if I missed it. 

I'm trying to write a generic stan program that can handle any mixed linear model (y = X*b + Z*u + e) and have a solution that mostly works. The trouble is that my design matrix (X) or random variable matrix (Z) can have zero, one or many columns. This creates a problem for my stan program because X and Z are declared as matrices and the heuristics inside rdump do not detect the desired data types. 

I'd like to make a feature request to declare variable types.  

If there is a work-around please let me know. If not, my solution was to create an RData object that keeps track of variable names, values and types and includes its own rdump routine. I then modified StanModel.set.data to detect whether the input is an RData object. If it is, then it calls RData.dump. Simple enough and it should be backward compatible. You are welcome to use my code for RData if you think it would be useful. Just email me.

**Comment by brian-lau** [comment]
I would appreciate seeing your solution. Do you mind posting or sending to me (brian.lau@upmc.fr). Thanks

**Comment by mboedigh** [comment]
Ok. I sent an email with the code and some notes on usage.

**Comment by brian-lau** [comment]
Got it thanks.

**Comment by genenk** [comment]
Could you please share your solution?

I have a problem that probably stems from the same issue. I have an int array with one or more elements, depending on the size of the incoming data. When the array has only one element I get the following error:
Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=W; dims declared=(1); dims found=()

I suppose the problem is the different representation of the data in temp.data.R:

temp.data.R with more than one element in W
W <- c(18, 15, 17, 15, 23, 17)
temp.data.R with one element in W
W <-18

Thanks

**Comment by mboedigh** [comment]
I'm happy to share, but I defer to Brian whether he wants ad-hoc patches floating around. It might be hard to support. Let me know.

**Comment by brian-lau** [comment]
I'll have something working in the dev branch today

**Comment by brian-lau** [comment]
I pushed Mike's solution to the dev branch. You can use the RData class to solve your problem.

d = RData(struct('x',1:10));

by default has type 'vector', declaring with a scalar 

d = RData(struct('x',1))

will by default create a scalar. In your case, you can override the default by

d.type('x') = 'vector'

which will produce a data file that looks like:

x <- c(1)

instead of 

x <- 1

which I think was causing your problem. 

Let me know if this doesn't work.

**Comment by genenk** [comment]
I tested it and it works a treat in my case.

Thank you both.
